#ifndef _PNG_ERROR_H_
#define _PNG_ERROR_H_

#define		PNG_INVALID_CHUNKTYPE						1
#define		PNG_INVALID_HEADER_CHUNK					2
#define		PNG_INVALID_GAMA_VALUE						3
#define 	PNG_INVALID_MODE							4
#define 	PNG_INVALID_SIGNATURE						5

#define		PNG_ZLIB_MEMORY_ERROR						6
#define		PNG_ZLIB_VERSION_ERROR						7
#define		PNG_UNKNOWN_ZLIB_ERROR						8
#define		PNG_ZLIB_ERROR								9

#define		PNG_ERROR_NOT_ENOUGH_DATA					10
#define		PNG_ZLIB_EXTRA_COMPRESSED_DATA				11

#define		PNG_INVALID_TRNS_CHUNK						12

#define		PNG_ERROR_IDAT_DETECTED_BEFORE_IHDR			13
#define		PNG_ERROR_ZERO_COLS							14
#define		PNG_ERROR_ZERO_ROWS							15
#define		PNG_INVALID_BIT_DEPTH						16
#define		PNG_INVALID_COLOUR_TYPE						17
#define		PNG_INVALID_COMPRESSION_METHOD				18
#define		PNG_INVALID_FILTER_METHOD					19
#define		PNG_INVALID_INTERLACE_METHOD				20

#endif
